// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mysql.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Username struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Username) Reset()         { *m = Username{} }
func (m *Username) String() string { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()    {}
func (*Username) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2c41a7352f42e6, []int{0}
}

func (m *Username) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Username.Unmarshal(m, b)
}
func (m *Username) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Username.Marshal(b, m, deterministic)
}
func (m *Username) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Username.Merge(m, src)
}
func (m *Username) XXX_Size() int {
	return xxx_messageInfo_Username.Size(m)
}
func (m *Username) XXX_DiscardUnknown() {
	xxx_messageInfo_Username.DiscardUnknown(m)
}

var xxx_messageInfo_Username proto.InternalMessageInfo

func (m *Username) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserInformation struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Photo                string   `protobuf:"bytes,5,opt,name=photo,proto3" json:"photo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInformation) Reset()         { *m = UserInformation{} }
func (m *UserInformation) String() string { return proto.CompactTextString(m) }
func (*UserInformation) ProtoMessage()    {}
func (*UserInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2c41a7352f42e6, []int{1}
}

func (m *UserInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInformation.Unmarshal(m, b)
}
func (m *UserInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInformation.Marshal(b, m, deterministic)
}
func (m *UserInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInformation.Merge(m, src)
}
func (m *UserInformation) XXX_Size() int {
	return xxx_messageInfo_UserInformation.Size(m)
}
func (m *UserInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInformation.DiscardUnknown(m)
}

var xxx_messageInfo_UserInformation proto.InternalMessageInfo

func (m *UserInformation) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInformation) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInformation) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInformation) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInformation) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

type Result struct {
	IsVaild              bool     `protobuf:"varint,1,opt,name=isVaild,proto3" json:"isVaild,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2c41a7352f42e6, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetIsVaild() bool {
	if m != nil {
		return m.IsVaild
	}
	return false
}

func (m *Result) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Value struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2c41a7352f42e6, []int{3}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Condition struct {
	Value                []*Value `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca2c41a7352f42e6, []int{4}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetValue() []*Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Username)(nil), "auth.Username")
	proto.RegisterType((*UserInformation)(nil), "auth.UserInformation")
	proto.RegisterType((*Result)(nil), "auth.Result")
	proto.RegisterType((*Value)(nil), "auth.Value")
	proto.RegisterType((*Condition)(nil), "auth.Condition")
}

func init() { proto.RegisterFile("mysql.proto", fileDescriptor_ca2c41a7352f42e6) }

var fileDescriptor_ca2c41a7352f42e6 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x19, 0xdb, 0xd4, 0xf4, 0x46, 0xa8, 0x0c, 0x0a, 0x21, 0xab, 0x9a, 0x85, 0x14, 0x84,
	0x68, 0x2b, 0x88, 0x7b, 0xdd, 0x74, 0xe1, 0xc2, 0x40, 0xbb, 0x1f, 0xcd, 0x48, 0x87, 0x4e, 0x66,
	0xe2, 0xcc, 0x44, 0xc9, 0x63, 0xf8, 0x6a, 0x3e, 0x91, 0xcc, 0x4f, 0x0a, 0xfe, 0xe2, 0xee, 0x9e,
	0xb9, 0xe7, 0xbb, 0x9c, 0x1c, 0x02, 0x49, 0xdd, 0xe9, 0x67, 0x5e, 0x34, 0x4a, 0x1a, 0x89, 0x87,
	0xa4, 0x35, 0x9b, 0xfc, 0x14, 0xe2, 0x95, 0xa6, 0x4a, 0x90, 0x9a, 0xe2, 0x0c, 0xe2, 0x36, 0xcc,
	0x29, 0x9a, 0xa2, 0xd9, 0xb8, 0xdc, 0xe9, 0xfc, 0x0d, 0xc1, 0xc4, 0x1a, 0x97, 0xe2, 0x49, 0xaa,
	0x9a, 0x18, 0x26, 0xc5, 0x5f, 0x7e, 0xbb, 0x6b, 0x88, 0xd6, 0xaf, 0x52, 0x55, 0xe9, 0x9e, 0xdf,
	0xf5, 0x1a, 0x1f, 0x41, 0x44, 0x6b, 0xc2, 0x78, 0x3a, 0x70, 0x0b, 0x2f, 0x2c, 0x21, 0xd8, 0xe3,
	0xd6, 0x5d, 0x1b, 0x7a, 0xa2, 0xd7, 0x96, 0x68, 0x36, 0xd2, 0xc8, 0x34, 0xf2, 0x84, 0x13, 0xf9,
	0x35, 0x8c, 0x4a, 0xaa, 0x5b, 0x6e, 0x70, 0x0a, 0xfb, 0x4c, 0xaf, 0x09, 0xe3, 0x95, 0x0b, 0x12,
	0x97, 0xbd, 0xb4, 0xe4, 0x0b, 0xe1, 0x2d, 0x0d, 0x21, 0xbc, 0xc8, 0xcf, 0x21, 0x5a, 0xdb, 0x01,
	0x1f, 0xc2, 0x60, 0x4b, 0xbb, 0x90, 0xde, 0x8e, 0xbf, 0x00, 0x05, 0x8c, 0x6f, 0xa4, 0xa8, 0x98,
	0xfb, 0xee, 0x93, 0xde, 0x82, 0xa6, 0x83, 0x59, 0xb2, 0x48, 0x0a, 0xdb, 0x64, 0xe1, 0x0e, 0x06,
	0xff, 0xe2, 0x1d, 0x41, 0x74, 0x67, 0xcb, 0xc6, 0x57, 0x00, 0xf7, 0x2d, 0x55, 0x9d, 0x2d, 0x4f,
	0xe3, 0x89, 0xf7, 0xee, 0x6e, 0x65, 0xc7, 0xfe, 0xe1, 0x4b, 0xb5, 0x17, 0x08, 0xcf, 0x01, 0x96,
	0x42, 0x53, 0x65, 0xec, 0x0a, 0xff, 0x6c, 0xcb, 0x0e, 0xfc, 0x73, 0x68, 0x61, 0x0e, 0xb0, 0x6a,
	0x2a, 0x62, 0xe8, 0xff, 0x91, 0x33, 0x80, 0x5b, 0xca, 0x69, 0x40, 0xbe, 0xa5, 0xfb, 0x64, 0x7e,
	0x18, 0xb9, 0x1f, 0xe7, 0xf2, 0x23, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xca, 0xfd, 0x18, 0x47, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MysqlClient is the client API for Mysql service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MysqlClient interface {
	QueryUsers(ctx context.Context, in *Condition, opts ...grpc.CallOption) (Mysql_QueryUsersClient, error)
	InsertUser(ctx context.Context, in *UserInformation, opts ...grpc.CallOption) (*Result, error)
	UpdateUser(ctx context.Context, in *UserInformation, opts ...grpc.CallOption) (*Result, error)
	DeleteUser(ctx context.Context, in *Condition, opts ...grpc.CallOption) (*Result, error)
}

type mysqlClient struct {
	cc *grpc.ClientConn
}

func NewMysqlClient(cc *grpc.ClientConn) MysqlClient {
	return &mysqlClient{cc}
}

func (c *mysqlClient) QueryUsers(ctx context.Context, in *Condition, opts ...grpc.CallOption) (Mysql_QueryUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Mysql_serviceDesc.Streams[0], "/auth.Mysql/QueryUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &mysqlQueryUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Mysql_QueryUsersClient interface {
	Recv() (*UserInformation, error)
	grpc.ClientStream
}

type mysqlQueryUsersClient struct {
	grpc.ClientStream
}

func (x *mysqlQueryUsersClient) Recv() (*UserInformation, error) {
	m := new(UserInformation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mysqlClient) InsertUser(ctx context.Context, in *UserInformation, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/auth.Mysql/InsertUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mysqlClient) UpdateUser(ctx context.Context, in *UserInformation, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/auth.Mysql/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mysqlClient) DeleteUser(ctx context.Context, in *Condition, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/auth.Mysql/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MysqlServer is the server API for Mysql service.
type MysqlServer interface {
	QueryUsers(*Condition, Mysql_QueryUsersServer) error
	InsertUser(context.Context, *UserInformation) (*Result, error)
	UpdateUser(context.Context, *UserInformation) (*Result, error)
	DeleteUser(context.Context, *Condition) (*Result, error)
}

// UnimplementedMysqlServer can be embedded to have forward compatible implementations.
type UnimplementedMysqlServer struct {
}

func (*UnimplementedMysqlServer) QueryUsers(req *Condition, srv Mysql_QueryUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryUsers not implemented")
}
func (*UnimplementedMysqlServer) InsertUser(ctx context.Context, req *UserInformation) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertUser not implemented")
}
func (*UnimplementedMysqlServer) UpdateUser(ctx context.Context, req *UserInformation) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedMysqlServer) DeleteUser(ctx context.Context, req *Condition) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterMysqlServer(s *grpc.Server, srv MysqlServer) {
	s.RegisterService(&_Mysql_serviceDesc, srv)
}

func _Mysql_QueryUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Condition)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MysqlServer).QueryUsers(m, &mysqlQueryUsersServer{stream})
}

type Mysql_QueryUsersServer interface {
	Send(*UserInformation) error
	grpc.ServerStream
}

type mysqlQueryUsersServer struct {
	grpc.ServerStream
}

func (x *mysqlQueryUsersServer) Send(m *UserInformation) error {
	return x.ServerStream.SendMsg(m)
}

func _Mysql_InsertUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).InsertUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Mysql/InsertUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlServer).InsertUser(ctx, req.(*UserInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mysql_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Mysql/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlServer).UpdateUser(ctx, req.(*UserInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mysql_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Condition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MysqlServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Mysql/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MysqlServer).DeleteUser(ctx, req.(*Condition))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mysql_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Mysql",
	HandlerType: (*MysqlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertUser",
			Handler:    _Mysql_InsertUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Mysql_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Mysql_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryUsers",
			Handler:       _Mysql_QueryUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mysql.proto",
}
