// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mongodb.proto

package mongodb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProjectValue struct {
	Temp                 string   `protobuf:"bytes,1,opt,name=temp,proto3" json:"temp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectValue) Reset()         { *m = ProjectValue{} }
func (m *ProjectValue) String() string { return proto.CompactTextString(m) }
func (*ProjectValue) ProtoMessage()    {}
func (*ProjectValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_21010b45f990def2, []int{0}
}

func (m *ProjectValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectValue.Unmarshal(m, b)
}
func (m *ProjectValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectValue.Marshal(b, m, deterministic)
}
func (m *ProjectValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectValue.Merge(m, src)
}
func (m *ProjectValue) XXX_Size() int {
	return xxx_messageInfo_ProjectValue.Size(m)
}
func (m *ProjectValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectValue proto.InternalMessageInfo

func (m *ProjectValue) GetTemp() string {
	if m != nil {
		return m.Temp
	}
	return ""
}

type Username struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Username) Reset()         { *m = Username{} }
func (m *Username) String() string { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()    {}
func (*Username) Descriptor() ([]byte, []int) {
	return fileDescriptor_21010b45f990def2, []int{1}
}

func (m *Username) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Username.Unmarshal(m, b)
}
func (m *Username) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Username.Marshal(b, m, deterministic)
}
func (m *Username) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Username.Merge(m, src)
}
func (m *Username) XXX_Size() int {
	return xxx_messageInfo_Username.Size(m)
}
func (m *Username) XXX_DiscardUnknown() {
	xxx_messageInfo_Username.DiscardUnknown(m)
}

var xxx_messageInfo_Username proto.InternalMessageInfo

func (m *Username) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ProjectId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectId) Reset()         { *m = ProjectId{} }
func (m *ProjectId) String() string { return proto.CompactTextString(m) }
func (*ProjectId) ProtoMessage()    {}
func (*ProjectId) Descriptor() ([]byte, []int) {
	return fileDescriptor_21010b45f990def2, []int{2}
}

func (m *ProjectId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectId.Unmarshal(m, b)
}
func (m *ProjectId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectId.Marshal(b, m, deterministic)
}
func (m *ProjectId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectId.Merge(m, src)
}
func (m *ProjectId) XXX_Size() int {
	return xxx_messageInfo_ProjectId.Size(m)
}
func (m *ProjectId) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectId.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectId proto.InternalMessageInfo

func (m *ProjectId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectInformation struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 string        `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Value                *ProjectValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProjectInformation) Reset()         { *m = ProjectInformation{} }
func (m *ProjectInformation) String() string { return proto.CompactTextString(m) }
func (*ProjectInformation) ProtoMessage()    {}
func (*ProjectInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_21010b45f990def2, []int{3}
}

func (m *ProjectInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInformation.Unmarshal(m, b)
}
func (m *ProjectInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInformation.Marshal(b, m, deterministic)
}
func (m *ProjectInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInformation.Merge(m, src)
}
func (m *ProjectInformation) XXX_Size() int {
	return xxx_messageInfo_ProjectInformation.Size(m)
}
func (m *ProjectInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInformation proto.InternalMessageInfo

func (m *ProjectInformation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectInformation) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ProjectInformation) GetValue() *ProjectValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type Result struct {
	IsVaild              bool     `protobuf:"varint,1,opt,name=isVaild,proto3" json:"isVaild,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_21010b45f990def2, []int{4}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetIsVaild() bool {
	if m != nil {
		return m.IsVaild
	}
	return false
}

func (m *Result) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ProjectValue)(nil), "mongodb.ProjectValue")
	proto.RegisterType((*Username)(nil), "mongodb.Username")
	proto.RegisterType((*ProjectId)(nil), "mongodb.ProjectId")
	proto.RegisterType((*ProjectInformation)(nil), "mongodb.ProjectInformation")
	proto.RegisterType((*Result)(nil), "mongodb.Result")
}

func init() { proto.RegisterFile("mongodb.proto", fileDescriptor_21010b45f990def2) }

var fileDescriptor_21010b45f990def2 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xd4, 0x36, 0x1d, 0xad, 0x92, 0x41, 0x31, 0xa4, 0x97, 0xb2, 0x07, 0x29, 0x08,
	0x45, 0xea, 0xa5, 0x17, 0x0f, 0x86, 0x5c, 0x82, 0x08, 0x1a, 0x68, 0xef, 0xa9, 0x3b, 0x4a, 0x24,
	0xc9, 0x86, 0xcd, 0x46, 0xc8, 0xdf, 0xf0, 0x17, 0x4b, 0x9a, 0xdd, 0x50, 0x5b, 0x10, 0xbc, 0xcd,
	0xdb, 0x79, 0xfb, 0xbd, 0x99, 0x65, 0x61, 0x9c, 0x8b, 0xe2, 0x43, 0xf0, 0xcd, 0xbc, 0x94, 0x42,
	0x09, 0x1c, 0x6a, 0xc9, 0x18, 0x9c, 0xbd, 0x48, 0xf1, 0x49, 0x6f, 0x6a, 0x9d, 0x64, 0x35, 0x21,
	0xc2, 0xb1, 0xa2, 0xbc, 0xf4, 0xac, 0xa9, 0x35, 0x1b, 0xc5, 0xdb, 0x9a, 0xdd, 0x80, 0xb3, 0xaa,
	0x48, 0x16, 0x49, 0x4e, 0xe8, 0x83, 0x53, 0xeb, 0x5a, 0x7b, 0x7a, 0xcd, 0x26, 0x30, 0xd2, 0xac,
	0x88, 0xe3, 0x39, 0xd8, 0x29, 0xd7, 0x16, 0x3b, 0xe5, 0x8c, 0x00, 0x4d, 0xb3, 0x78, 0x17, 0x32,
	0x4f, 0x54, 0x2a, 0x8a, 0x7d, 0x57, 0x1b, 0xdf, 0xe2, 0x3c, 0xbb, 0x8b, 0x6f, 0x6b, 0xbc, 0x85,
	0x93, 0xaf, 0x76, 0x36, 0xef, 0x68, 0x6a, 0xcd, 0x4e, 0x17, 0x57, 0x73, 0xb3, 0xca, 0xee, 0xe0,
	0x71, 0xe7, 0x61, 0x4b, 0x18, 0xc4, 0x54, 0xd5, 0x99, 0x42, 0x0f, 0x86, 0x69, 0xb5, 0x4e, 0xd2,
	0xac, 0xe3, 0x3b, 0xb1, 0x91, 0x78, 0x69, 0x80, 0x5d, 0x4a, 0x27, 0x16, 0xdf, 0x36, 0x0c, 0x9f,
	0x5b, 0x72, 0x18, 0xe0, 0x13, 0x5c, 0xbf, 0xd6, 0x24, 0x1b, 0x9d, 0x50, 0x05, 0x4d, 0xff, 0x00,
	0x6e, 0x1f, 0x6f, 0x8e, 0xfc, 0xc9, 0xfe, 0x44, 0x3b, 0x1b, 0xde, 0x59, 0xf8, 0x00, 0xe3, 0xa8,
	0xa8, 0x48, 0x2a, 0xdd, 0xc5, 0xbf, 0xfc, 0xfe, 0x45, 0xdf, 0xd4, 0x7b, 0x3c, 0x82, 0xbb, 0x2a,
	0x79, 0xa2, 0x48, 0x9b, 0x83, 0x26, 0x0a, 0xff, 0x89, 0x58, 0x82, 0x1b, 0x52, 0x46, 0xbf, 0x11,
	0x78, 0x80, 0xe0, 0x07, 0x37, 0x37, 0x83, 0xed, 0x77, 0xb9, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0xaa, 0xe7, 0x3a, 0x3f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MongoDBClient is the client API for MongoDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MongoDBClient interface {
	QueryProjectsByUsername(ctx context.Context, in *Username, opts ...grpc.CallOption) (MongoDB_QueryProjectsByUsernameClient, error)
	InsertProject(ctx context.Context, in *ProjectInformation, opts ...grpc.CallOption) (*Result, error)
	UpdateProjectByID(ctx context.Context, in *ProjectInformation, opts ...grpc.CallOption) (*Result, error)
	DeleteProjectByID(ctx context.Context, in *ProjectId, opts ...grpc.CallOption) (*Result, error)
}

type mongoDBClient struct {
	cc *grpc.ClientConn
}

func NewMongoDBClient(cc *grpc.ClientConn) MongoDBClient {
	return &mongoDBClient{cc}
}

func (c *mongoDBClient) QueryProjectsByUsername(ctx context.Context, in *Username, opts ...grpc.CallOption) (MongoDB_QueryProjectsByUsernameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MongoDB_serviceDesc.Streams[0], "/mongodb.MongoDB/QueryProjectsByUsername", opts...)
	if err != nil {
		return nil, err
	}
	x := &mongoDBQueryProjectsByUsernameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MongoDB_QueryProjectsByUsernameClient interface {
	Recv() (*ProjectInformation, error)
	grpc.ClientStream
}

type mongoDBQueryProjectsByUsernameClient struct {
	grpc.ClientStream
}

func (x *mongoDBQueryProjectsByUsernameClient) Recv() (*ProjectInformation, error) {
	m := new(ProjectInformation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mongoDBClient) InsertProject(ctx context.Context, in *ProjectInformation, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/mongodb.MongoDB/InsertProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoDBClient) UpdateProjectByID(ctx context.Context, in *ProjectInformation, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/mongodb.MongoDB/UpdateProjectByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mongoDBClient) DeleteProjectByID(ctx context.Context, in *ProjectId, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/mongodb.MongoDB/DeleteProjectByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MongoDBServer is the server API for MongoDB service.
type MongoDBServer interface {
	QueryProjectsByUsername(*Username, MongoDB_QueryProjectsByUsernameServer) error
	InsertProject(context.Context, *ProjectInformation) (*Result, error)
	UpdateProjectByID(context.Context, *ProjectInformation) (*Result, error)
	DeleteProjectByID(context.Context, *ProjectId) (*Result, error)
}

// UnimplementedMongoDBServer can be embedded to have forward compatible implementations.
type UnimplementedMongoDBServer struct {
}

func (*UnimplementedMongoDBServer) QueryProjectsByUsername(req *Username, srv MongoDB_QueryProjectsByUsernameServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryProjectsByUsername not implemented")
}
func (*UnimplementedMongoDBServer) InsertProject(ctx context.Context, req *ProjectInformation) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertProject not implemented")
}
func (*UnimplementedMongoDBServer) UpdateProjectByID(ctx context.Context, req *ProjectInformation) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProjectByID not implemented")
}
func (*UnimplementedMongoDBServer) DeleteProjectByID(ctx context.Context, req *ProjectId) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProjectByID not implemented")
}

func RegisterMongoDBServer(s *grpc.Server, srv MongoDBServer) {
	s.RegisterService(&_MongoDB_serviceDesc, srv)
}

func _MongoDB_QueryProjectsByUsername_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Username)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MongoDBServer).QueryProjectsByUsername(m, &mongoDBQueryProjectsByUsernameServer{stream})
}

type MongoDB_QueryProjectsByUsernameServer interface {
	Send(*ProjectInformation) error
	grpc.ServerStream
}

type mongoDBQueryProjectsByUsernameServer struct {
	grpc.ServerStream
}

func (x *mongoDBQueryProjectsByUsernameServer) Send(m *ProjectInformation) error {
	return x.ServerStream.SendMsg(m)
}

func _MongoDB_InsertProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDBServer).InsertProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodb.MongoDB/InsertProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDBServer).InsertProject(ctx, req.(*ProjectInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoDB_UpdateProjectByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDBServer).UpdateProjectByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodb.MongoDB/UpdateProjectByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDBServer).UpdateProjectByID(ctx, req.(*ProjectInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _MongoDB_DeleteProjectByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MongoDBServer).DeleteProjectByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongodb.MongoDB/DeleteProjectByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MongoDBServer).DeleteProjectByID(ctx, req.(*ProjectId))
	}
	return interceptor(ctx, in, info, handler)
}

var _MongoDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mongodb.MongoDB",
	HandlerType: (*MongoDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertProject",
			Handler:    _MongoDB_InsertProject_Handler,
		},
		{
			MethodName: "UpdateProjectByID",
			Handler:    _MongoDB_UpdateProjectByID_Handler,
		},
		{
			MethodName: "DeleteProjectByID",
			Handler:    _MongoDB_DeleteProjectByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryProjectsByUsername",
			Handler:       _MongoDB_QueryProjectsByUsername_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mongodb.proto",
}
